// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Branch struct {
	ID         int64          `json:"id"`
	RepoPath   string         `json:"repo_path"`
	Name       string         `json:"name"`
	Locked     int64          `json:"locked"`
	LockedBy   sql.NullInt64  `json:"locked_by"`
	LockedAt   sql.NullString `json:"locked_at"`
	LastSeenAt string         `json:"last_seen_at"`
}

type PendingComment struct {
	ID              string         `json:"id"`
	UserID          int64          `json:"user_id"`
	RepoRoot        string         `json:"repo_root"`
	ContextKind     string         `json:"context_kind"`
	ContextSha      string         `json:"context_sha"`
	FilePath        string         `json:"file_path"`
	DiffSection     string         `json:"diff_section"`
	Side            string         `json:"side"`
	LineNumber      int64          `json:"line_number"`
	StartLineNumber sql.NullInt64  `json:"start_line_number"`
	StartSide       sql.NullString `json:"start_side"`
	AuthorLabel     string         `json:"author_label"`
	BodyHtml        string         `json:"body_html"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
}

type Repository struct {
	Path         string         `json:"path"`
	Name         string         `json:"name"`
	OwnerID      int64          `json:"owner_id"`
	AddedAt      string         `json:"added_at"`
	LastOpenedAt sql.NullString `json:"last_opened_at"`
}

type RepositoryUser struct {
	RepoPath  string `json:"repo_path"`
	UserID    int64  `json:"user_id"`
	Role      string `json:"role"`
	GrantedAt string `json:"granted_at"`
}

type ReviewComment struct {
	ID              string         `json:"id"`
	ReviewID        string         `json:"review_id"`
	FilePath        string         `json:"file_path"`
	DiffSection     string         `json:"diff_section"`
	Side            string         `json:"side"`
	LineNumber      int64          `json:"line_number"`
	StartLineNumber sql.NullInt64  `json:"start_line_number"`
	StartSide       sql.NullString `json:"start_side"`
	AuthorLabel     string         `json:"author_label"`
	BodyHtml        string         `json:"body_html"`
	CreatedAt       string         `json:"created_at"`
	UpdatedAt       string         `json:"updated_at"`
	DeletedAt       sql.NullString `json:"deleted_at"`
}

type ReviewEvent struct {
	ID        int64  `json:"id"`
	ReviewID  string `json:"review_id"`
	EventType string `json:"event_type"`
	FilePath  string `json:"file_path"`
	Message   string `json:"message"`
	Metadata  string `json:"metadata"`
	CreatedAt string `json:"created_at"`
}

type ReviewSession struct {
	ID           string         `json:"id"`
	RepoRoot     string         `json:"repo_root"`
	UserID       int64          `json:"user_id"`
	Branch       string         `json:"branch"`
	HeadSha      string         `json:"head_sha"`
	Status       string         `json:"status"`
	Title        string         `json:"title"`
	Summary      string         `json:"summary"`
	FilesChanged int64          `json:"files_changed"`
	Additions    int64          `json:"additions"`
	Deletions    int64          `json:"deletions"`
	StartedAt    string         `json:"started_at"`
	CompletedAt  sql.NullString `json:"completed_at"`
	ContextKind  string         `json:"context_kind"`
	ContextSha   sql.NullString `json:"context_sha"`
}

type UiPreference struct {
	UserID    int64  `json:"user_id"`
	Key       string `json:"key"`
	Value     string `json:"value"`
	UpdatedAt string `json:"updated_at"`
}

type User struct {
	ID           int64  `json:"id"`
	OsUsername   string `json:"os_username"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
	CreatedAt    string `json:"created_at"`
	LastLoginAt  string `json:"last_login_at"`
}

type UserSession struct {
	Token      string `json:"token"`
	UserID     int64  `json:"user_id"`
	CreatedAt  string `json:"created_at"`
	ExpiresAt  string `json:"expires_at"`
	LastUsedAt string `json:"last_used_at"`
}

type Walkthrough struct {
	RepoRoot    string `json:"repo_root"`
	ContextKind string `json:"context_kind"`
	ContextSha  string `json:"context_sha"`
	Fingerprint string `json:"fingerprint"`
	ProviderID  string `json:"provider_id"`
	ModelID     string `json:"model_id"`
	GroupsJson  string `json:"groups_json"`
	Summary     string `json:"summary"`
	GeneratedAt string `json:"generated_at"`
}
