// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const __noop = `-- name: __noop :exec
SELECT 1
`

// sqlc requires at least one query; all storage methods are written directly in store.go.
func (q *Queries) __noop(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, __noop)
	return err
}
