// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type UserPreference struct {
	ID        int64  `json:"id"`
	Theme     string `json:"theme"`
	UpdatedAt string `json:"updated_at"`
}

type WorkflowEvent struct {
	ID        int64          `json:"id"`
	RunID     string         `json:"run_id"`
	Seq       int64          `json:"seq"`
	EventType string         `json:"event_type"`
	PhaseID   sql.NullString `json:"phase_id"`
	PhaseName sql.NullString `json:"phase_name"`
	Status    sql.NullString `json:"status"`
	Message   sql.NullString `json:"message"`
	CreatedAt string         `json:"created_at"`
}

type WorkflowRun struct {
	ID                      string         `json:"id"`
	WorkflowID              string         `json:"workflow_id"`
	WorkflowName            string         `json:"workflow_name"`
	ConfirmationOptionID    string         `json:"confirmation_option_id"`
	ConfirmationOptionLabel string         `json:"confirmation_option_label"`
	Mode                    string         `json:"mode"`
	Status                  string         `json:"status"`
	StartedAt               string         `json:"started_at"`
	CompletedAt             sql.NullString `json:"completed_at"`
	ErrorMessage            sql.NullString `json:"error_message"`
}
