// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const completeRun = `-- name: CompleteRun :exec
UPDATE workflow_runs
SET status = ?, completed_at = ?, error_message = ?
WHERE id = ?
`

type CompleteRunParams struct {
	Status       string         `json:"status"`
	CompletedAt  sql.NullString `json:"completed_at"`
	ErrorMessage sql.NullString `json:"error_message"`
	ID           string         `json:"id"`
}

func (q *Queries) CompleteRun(ctx context.Context, arg CompleteRunParams) error {
	_, err := q.db.ExecContext(ctx, completeRun,
		arg.Status,
		arg.CompletedAt,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}

const createRun = `-- name: CreateRun :exec
INSERT INTO workflow_runs (
  id,
  workflow_id,
  workflow_name,
  confirmation_option_id,
  confirmation_option_label,
  mode,
  status,
  started_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateRunParams struct {
	ID                      string `json:"id"`
	WorkflowID              string `json:"workflow_id"`
	WorkflowName            string `json:"workflow_name"`
	ConfirmationOptionID    string `json:"confirmation_option_id"`
	ConfirmationOptionLabel string `json:"confirmation_option_label"`
	Mode                    string `json:"mode"`
	Status                  string `json:"status"`
	StartedAt               string `json:"started_at"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) error {
	_, err := q.db.ExecContext(ctx, createRun,
		arg.ID,
		arg.WorkflowID,
		arg.WorkflowName,
		arg.ConfirmationOptionID,
		arg.ConfirmationOptionLabel,
		arg.Mode,
		arg.Status,
		arg.StartedAt,
	)
	return err
}

const getRun = `-- name: GetRun :one
SELECT
  id,
  workflow_id,
  workflow_name,
  confirmation_option_id,
  confirmation_option_label,
  mode,
  status,
  started_at,
  completed_at,
  error_message
FROM workflow_runs
WHERE id = ?
`

func (q *Queries) GetRun(ctx context.Context, id string) (WorkflowRun, error) {
	row := q.db.QueryRowContext(ctx, getRun, id)
	var i WorkflowRun
	err := row.Scan(
		&i.ID,
		&i.WorkflowID,
		&i.WorkflowName,
		&i.ConfirmationOptionID,
		&i.ConfirmationOptionLabel,
		&i.Mode,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.ErrorMessage,
	)
	return i, err
}

const getUserPreferences = `-- name: GetUserPreferences :one
SELECT theme, updated_at
FROM user_preferences
WHERE id = 1
`

type GetUserPreferencesRow struct {
	Theme     string `json:"theme"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) GetUserPreferences(ctx context.Context) (GetUserPreferencesRow, error) {
	row := q.db.QueryRowContext(ctx, getUserPreferences)
	var i GetUserPreferencesRow
	err := row.Scan(&i.Theme, &i.UpdatedAt)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO workflow_events (
  run_id,
  seq,
  event_type,
  phase_id,
  phase_name,
  status,
  message,
  created_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertEventParams struct {
	RunID     string         `json:"run_id"`
	Seq       int64          `json:"seq"`
	EventType string         `json:"event_type"`
	PhaseID   sql.NullString `json:"phase_id"`
	PhaseName sql.NullString `json:"phase_name"`
	Status    sql.NullString `json:"status"`
	Message   sql.NullString `json:"message"`
	CreatedAt string         `json:"created_at"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.RunID,
		arg.Seq,
		arg.EventType,
		arg.PhaseID,
		arg.PhaseName,
		arg.Status,
		arg.Message,
		arg.CreatedAt,
	)
	return err
}

const listRunEvents = `-- name: ListRunEvents :many
SELECT
  id,
  run_id,
  seq,
  event_type,
  phase_id,
  phase_name,
  status,
  message,
  created_at
FROM workflow_events
WHERE run_id = ?
ORDER BY seq ASC
`

func (q *Queries) ListRunEvents(ctx context.Context, runID string) ([]WorkflowEvent, error) {
	rows, err := q.db.QueryContext(ctx, listRunEvents, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowEvent{}
	for rows.Next() {
		var i WorkflowEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Seq,
			&i.EventType,
			&i.PhaseID,
			&i.PhaseName,
			&i.Status,
			&i.Message,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRuns = `-- name: ListRuns :many
SELECT
  id,
  workflow_id,
  workflow_name,
  confirmation_option_id,
  confirmation_option_label,
  mode,
  status,
  started_at,
  completed_at,
  error_message
FROM workflow_runs
ORDER BY started_at DESC
LIMIT ?
`

func (q *Queries) ListRuns(ctx context.Context, limit int64) ([]WorkflowRun, error) {
	rows, err := q.db.QueryContext(ctx, listRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowRun{}
	for rows.Next() {
		var i WorkflowRun
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowID,
			&i.WorkflowName,
			&i.ConfirmationOptionID,
			&i.ConfirmationOptionLabel,
			&i.Mode,
			&i.Status,
			&i.StartedAt,
			&i.CompletedAt,
			&i.ErrorMessage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserPreferences = `-- name: UpsertUserPreferences :exec
INSERT INTO user_preferences (id, theme, updated_at)
VALUES (1, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  theme = excluded.theme,
  updated_at = excluded.updated_at
`

type UpsertUserPreferencesParams struct {
	Theme     string `json:"theme"`
	UpdatedAt string `json:"updated_at"`
}

func (q *Queries) UpsertUserPreferences(ctx context.Context, arg UpsertUserPreferencesParams) error {
	_, err := q.db.ExecContext(ctx, upsertUserPreferences, arg.Theme, arg.UpdatedAt)
	return err
}
