import type { EditorThemeClasses } from 'lexical';

export const editorTheme: EditorThemeClasses = {
	paragraph: 'rte-paragraph',
	quote: 'rte-quote',
	heading: {
		h1: 'rte-h1',
		h2: 'rte-h2',
		h3: 'rte-h3',
		h4: 'rte-h4',
		h5: 'rte-h5',
		h6: 'rte-h6',
	},
	list: {
		nested: {
			listitem: 'rte-nested-listitem',
		},
		ol: 'rte-list-ol',
		ul: 'rte-list-ul',
		listitem: 'rte-listitem',
		listitemChecked: 'rte-listitem-checked',
		listitemUnchecked: 'rte-listitem-unchecked',
	},
	link: 'rte-link',
	text: {
		bold: 'rte-text-bold',
		italic: 'rte-text-italic',
		underline: 'rte-text-underline',
		strikethrough: 'rte-text-strikethrough',
		underlineStrikethrough: 'rte-text-underline-strikethrough',
		code: 'rte-text-code',
	},
	code: 'rte-code-block',
	codeHighlight: {
		atrule: 'rte-tok-attr',
		attr: 'rte-tok-attr',
		boolean: 'rte-tok-boolean',
		builtin: 'rte-tok-builtin',
		cdata: 'rte-tok-comment',
		char: 'rte-tok-string',
		class: 'rte-tok-class',
		'class-name': 'rte-tok-class',
		comment: 'rte-tok-comment',
		constant: 'rte-tok-constant',
		deleted: 'rte-tok-deleted',
		doctype: 'rte-tok-comment',
		entity: 'rte-tok-entity',
		function: 'rte-tok-function',
		important: 'rte-tok-important',
		inserted: 'rte-tok-inserted',
		keyword: 'rte-tok-keyword',
		namespace: 'rte-tok-namespace',
		number: 'rte-tok-number',
		operator: 'rte-tok-operator',
		prolog: 'rte-tok-comment',
		property: 'rte-tok-property',
		punctuation: 'rte-tok-punctuation',
		regex: 'rte-tok-regex',
		selector: 'rte-tok-selector',
		string: 'rte-tok-string',
		symbol: 'rte-tok-symbol',
		tag: 'rte-tok-tag',
		url: 'rte-tok-url',
		variable: 'rte-tok-variable',
	},
	table: 'rte-table',
	tableCell: 'rte-table-cell',
	tableCellHeader: 'rte-table-cell-header',
	tableRow: 'rte-table-row',
	image: 'rte-image',
	mention: 'rte-mention',
	hashtag: 'rte-hashtag',
	horizontalRule: 'rte-hr',
};
